### ISSUE TITLE
Customize indentation with `clips-indent-function`

### ISSUE THREAD

**Issue by dram** [grettke/clips-mode#16]
In Lisp and Scheme mode, indentation can be customized with `lisp-indent-function` and `scheme-indent-function` property of specific symbol. it would be nice if CLIPS mode can support this. e.g.

```
(put 'foreach 'clips-indent-function 2)
```

Currently, I need to use `lisp-indent-function` instead of `clips-indent-function`.

**Comment by grettke** [comment]
I hear you. What are you ideas on how this would look in use?

**Comment by dram** [comment]
Currently, indentation of `foreach`, `do-for-fact` and some other structures is not quite good. e.g.

```
(foreach ?v ?vs
         do-something
         do-something-other)
```

With the help of `clips-indent-function` support, it can be indented as:

```
(foreach ?v ?vs
  do-something
  do-something-other)
```

See https://github.com/dram/configs/commit/4e9f21d2676e048d0a6a4f833c1ba4630eb5e1b0

**Comment by grettke** [comment]
Gotcha. Can you implement this feature?

**Comment by dram** [comment]
Will have a try.

**Comment by grettke** [comment]
@dram Thank you.
